version: '0.01'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./:/usr/share
      - ./server-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
  nginxclient:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./client/dist:/usr/share
      - ./server-conf/nginx-client.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
  php:
    container_name: php
    build:
      dockerfile: ./server-conf/dockerfile
      context: .
    # ports:
    #   - 9000:9000
    #   - 9001:9001
    volumes:
      - ./:/usr/share
      - ./server-conf/php.ini:/usr/local/etc/php/php.ini
      - ./server-conf/fpm.conf:/usr/local/etc/php-fpm.d/fpm.conf
    networks:
      - internal
  phpcmd:
    # image: php:8.3-alpine
    container_name: phpcmd
    build:
      dockerfile: ./server-conf/dockerfilephpcmd
      context: .
    volumes:
      - ./:/usr/share
      - ./server-conf/php.ini:/usr/local/etc/php/php.ini
    command:
      - sh
      - "-c"
      - |
        cd /usr/share
        sleep 10 && php artisan queue:work
    depends_on:
      rabbitmq:
        condition: service_started
    networks:
      - internal
  mysql:
    image: mysql:8.0.39
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: phpblog_db
      MYSQL_USER: phpblog_user
      MYSQL_PASSWORD: phpblog_password
    # volumes:
    #   - './mysqldata:/var/lib/mysql'
    networks:
      - internal
  redis-host:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - internal
  memcached-host:
    image: memcached:latest
    ports:
      - 11211:11211
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    networks:
      - internal
  socketio:
    image: node:lts-alpine
    volumes:
      - ./socketio:/usr/share
    ports:
      - 3000:3000
    command:
      - sh
      - "-c"
      - |
        cd /usr/share && npm start
    networks:
      - internal
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - internal
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - internal
networks:
  internal:
    driver: bridge

# Volumes
# volumes:
#   mysqldata: