apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      initContainers:
      - name: initcode
        image: node:lts-alpine
        command:
        - sh
        - "-c"
        - |
          cd /usr/share/nginx/html
          apk add --no-cache git && git clone https://github.com/luan4637/vuejs-blog.git .
          git reset --hard && git pull
          cd /usr/share/nginx/html/client
          npm install && npm run build
          cd /usr/share/nginx/html/clientAdmin
          npm install && npm run build
        volumeMounts:
        - name: sourcecode-volume
          mountPath: /usr/share/nginx/html
        # - name: client-pvc
        #   mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        # - name: client-pvc
        #   mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: sourcecode-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: client-configmap
      - name: sourcecode-volume
        emptyDir:
          sizeLimit: 500Mi
  # volumeClaimTemplates:
  # - metadata:
  #     name: client-pvc
  #   spec:
  #     accessModes: ["ReadWriteOnce"]
  #     resources:
  #       requests:
  #         storage: 500Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap
data:
  nginx.conf: |
    server {
      listen 80;
      server_name admin.vueblog.private;
      index index.html;

      root /usr/share/nginx/html/clientAdmin/dist;
    }

    server {
      listen 80;
      server_name vueblog.private;
      index index.html;

      root /usr/share/nginx/html/client/dist;
    }
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: client