apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/share/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/share/mysql1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/share/mysql2"
---